apiVersion: 1

datasources:
  - name: JamTart API
    type: yesoreyeram-infinity-datasource
    uid: jamtart-api
    access: proxy
    isDefault: false
    editable: true
    jsonData:
      global_queries: []
      allowedHosts:
        - http://localhost:8080
        - http://localhost:8080
